"""crear tabla farmacia y turno

Revision ID: 6b069d06d1d4
Revises: 
Create Date: 2025-06-16 21:36:58.074499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b069d06d1d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmacias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmacias_id'), 'farmacias', ['id'], unique=False)
    op.create_table('turno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_farmacia', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_farmacia'], ['farmacias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turno_id'), 'turno', ['id'], unique=False)
    op.create_index(op.f('ix_turno_id_farmacia'), 'turno', ['id_farmacia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_id_farmacia'), table_name='turno')
    op.drop_index(op.f('ix_turno_id'), table_name='turno')
    op.drop_table('turno')
    op.drop_index(op.f('ix_farmacias_id'), table_name='farmacias')
    op.drop_table('farmacias')
    # ### end Alembic commands ###
